#!/usr/bin/env python3
"""Generate a markdown report with PlatformIO registry metrics."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen


API_BASE = "https://api.registry.platformio.org/v3"


def fetch_json(url: str) -> Dict[str, Any]:
    request = Request(url, headers={"User-Agent": "C-Arduino-Libraries/metrics-bot"})
    try:
        with urlopen(request, timeout=30) as response:
            payload = response.read().decode("utf-8")
            return json.loads(payload)
    except HTTPError as exc:
        raise RuntimeError(f"HTTP {exc.code} for {url}") from exc
    except URLError as exc:
        raise RuntimeError(f"Network error for {url}: {exc}") from exc


def fetch_owner_packages(owner: str) -> List[Dict[str, Any]]:
    items: List[Dict[str, Any]] = []
    page = 1
    limit = 50

    while True:
        query = urlencode({"query": f"owner:{owner}", "limit": limit, "page": page})
        url = f"{API_BASE}/search?{query}"
        data = fetch_json(url)

        page_items = data.get("items") or []
        if not page_items:
            break

        items.extend(page_items)
        total = int(data.get("total") or 0)

        if len(items) >= total or len(page_items) < limit:
            break
        page += 1

    return [pkg for pkg in items if pkg.get("type") == "library"]


def fetch_search_total(query_text: str) -> int:
    query = urlencode({"query": query_text, "limit": 1, "page": 1})
    url = f"{API_BASE}/search?{query}"
    data = fetch_json(url)
    return int(data.get("total") or 0)


def fetch_package_details(owner: str, name: str) -> Dict[str, Any]:
    owner_encoded = quote(owner, safe="")
    name_encoded = quote(name, safe="")
    url = f"{API_BASE}/packages/{owner_encoded}/library/{name_encoded}"
    return fetch_json(url)


def format_num(value: Any) -> str:
    if value is None:
        return "N/A"
    return str(value)


def format_trend(value: Any) -> str:
    if value is None:
        return "N/A"
    try:
        number = int(value)
    except (TypeError, ValueError):
        return str(value)
    if number > 0:
        return f"+{number}"
    return str(number)


def build_markdown(owner: str, packages: List[Dict[str, Any]], owner_total: int, global_library_total: int) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    owner_library_total = len(packages)
    if global_library_total > 0:
        share = (owner_library_total / global_library_total) * 100.0
        share_text = f"{share:.2f}%"
    else:
        share_text = "N/A"

    lines = [
        "# PlatformIO Metrics Report",
        "",
        f"Source owner query: `{owner}`",
        f"Generated: `{generated_at}`",
        "",
        "This file is auto-generated by `.github/workflows/update-platformio-metrics.yml`.",
        "",
        "## Registry Comparison",
        "",
        f"- Global libraries in PlatformIO Registry: **{global_library_total}**",
        f"- Owner packages matched by query (`owner:{owner}`): **{owner_total}**",
        f"- Owner libraries in this report: **{owner_library_total}**",
        f"- Owner library share of global libraries: **{share_text}**",
        "",
        "## Notes",
        "",
        "- PlatformIO public API currently exposes rank/trend style metrics reliably.",
        "- The API does not provide a simple public `monthly_downloads` and `total_downloads` pair per package in this report.",
        "- `Download Trend` is included from `downloads_trend` where available.",
        "",
        "## Libraries",
        "",
        "| Library | Version | Popularity Rank | Rank Trend | Download Trend | Dependents | Stars | Last Updated |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]

    for pkg in packages:
        name = str(pkg.get("name") or "Unknown")
        version = str((pkg.get("version") or {}).get("name") or "N/A")
        rank = format_num(pkg.get("popularity_rank"))
        rank_trend = format_trend(pkg.get("popularity_trend"))
        download_trend = format_trend(pkg.get("downloads_trend"))
        dependents = format_num(pkg.get("dependents_count"))
        stars = format_num(pkg.get("stars_count"))
        updated = str(pkg.get("updated_at") or "N/A")

        lines.append(
            f"| {name} | {version} | {rank} | {rank_trend} | {download_trend} | {dependents} | {stars} | {updated} |"
        )

    lines.extend(
        [
            "",
            "## Raw API Endpoints Used",
            "",
            f"- Global libraries total: `{API_BASE}/search?query=type:library&limit=1&page=1`",
            f"- Search: `{API_BASE}/search?query=owner:{owner}&limit=50&page=1`",
            f"- Package details: `{API_BASE}/packages/{owner}/library/<name>`",
            "",
        ]
    )

    return "\n".join(lines)


def enrich_packages(owner: str, packages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    enriched: List[Dict[str, Any]] = []

    for item in packages:
        name = item.get("name")
        if not name:
            continue

        merged = dict(item)
        try:
            details = fetch_package_details(owner, str(name))
            for key in ("downloads_trend", "dependents_count", "updated_at", "stars_count", "popularity_rank", "popularity_trend"):
                if key in details:
                    merged[key] = details.get(key)
        except RuntimeError as exc:
            print(f"Warning: failed to fetch details for {name}: {exc}", file=sys.stderr)

        enriched.append(merged)

    enriched.sort(key=lambda pkg: (pkg.get("popularity_rank") is None, pkg.get("popularity_rank") or 10**9, str(pkg.get("name") or "")))
    return enriched


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate PlatformIO metrics markdown report")
    parser.add_argument("--owner", default="braydenanderson2014", help="PlatformIO owner username")
    parser.add_argument(
        "--output",
        default="PLATFORMIO_METRICS.md",
        help="Output markdown file path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    owner_total = fetch_search_total(f"owner:{args.owner}")
    global_library_total = fetch_search_total("type:library")
    packages = fetch_owner_packages(args.owner)
    enriched = enrich_packages(args.owner, packages)
    markdown = build_markdown(args.owner, enriched, owner_total, global_library_total)

    output_path = Path(args.output)
    output_path.write_text(markdown + "\n", encoding="utf-8")
    print(f"Wrote {len(enriched)} libraries to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
